### ISSUE TITLE
Default zoom-level should always show the complete image

### ISSUE THREAD

**Issue by Fiona-J-W** [CVVisualPSETeam/CVVisual#12]
I guess the best default zoomlevel would be:

1:1 if there is enough space
downscaled image so that everything can be seen on it otherwise

**Comment by ZockerAbc** [comment]
fullImage() must be called after the "final" layout was set, or in the first call of a resizeevent otherwise its useless

**Comment by Fiona-J-W** [comment]
wont fix further
