### ISSUE TITLE
Leak in OverviewTableRow?

### ISSUE THREAD

**Issue by Fiona-J-W** [CVVisualPSETeam/CVVisual#19]
Are the Items in the OverviewTable deleted?

**Comment by parttimenerd** [comment]
I don't delete them explicetly...

**Comment by parttimenerd** [comment]
But according to http://www.qtcentre.org/threads/28470-Does-QTableWidget-clear%28%29-delete-pointers , maybe calling qTable->clear() in the destructor of the OverviewGroupsubtable class might help.

**Comment by Fiona-J-W** [comment]
Well, the issue basically asks you to do some research ;-)

**Comment by parttimenerd** [comment]
I know. And I've done some...

But I really don't know why you expect leaks in this piece of code?

**Comment by Fiona-J-W** [comment]
Because there is an exceptional amount of new and naked pointers inside, many leaks in case of an exception and I don't see the stuff being given a parent.

I am however optimistic now, that the QTable-dtor will do that.

Nonetheless: Really consider using std::unique_ptr there and pass them into QTable::setItem via item.release().
