### ISSUE TITLE
segfault in stfl-engine with combined requests

### ISSUE THREAD

**Issue by Fiona-J-W** [CVVisualPSETeam/CVVisual#28]
I managed to make Andi's test-application segfault by filtering and grouping stuff in the overview. The stack-trace in the core can be found here: https://gist.github.com/Florianjw/9380713

**Comment by parttimenerd** [comment]
According to your stack trace, the problem arises not in STFLEngine, but in the Overview*Table.

**Comment by parttimenerd** [comment]
This stack trace alone (without the typed commands) doesn't help me, as I can't reproduce your error. (Some tracepoints would be also nice.)

**Comment by Fiona-J-W** [comment]
I would have provided you with these, if I had them. This happened in a release-build, I am happy that there was after all a usable stack-trace.

**Comment by parttimenerd** [comment]
Hmmm... I forgot, that you have to use the result build.
The only information I get from this stack trace is, that the problem might be in one of the following areas:
1. Accordion::clear
2. OverviewTable (add sub table to the accordion)

**Comment by parttimenerd** [comment]
As I'm currently unable to run Andi's application, it's impossible for my to debug this error.
