### ISSUE TITLE
Right-click-menu does not work with unique but random call-ids

### ISSUE THREAD

**Issue by Fiona-J-W** [CVVisualPSETeam/CVVisual#3]
After replacing the implementation of cvv::impl::newCallId() with this:

size_t newCallId()
{
    thread_local std::mt19937 gen{std::random_device{}()};
    return gen();
}

None of the options in the right-klick-menu of the overview tab work anymore.

Note: I am aware that the above is no correct generator for unique Ids. It will however most likely work fine if only a very small number (10) of IDs are ever requested and is therefore sufficient for testing-purposes.

**Comment by parttimenerd** [comment]
Is there any test case that I'm able to use to reproduce your findings.
And please give my the Tracepoint output of your right clicking action.

**Comment by Fiona-J-W** [comment]
Just tryout the manual tests in the random_ids branch. Also: The problem seems to not appear for the first call, only for all following.

To get tracepoints just execute yourself
