### ISSUE TITLE
Some tests not commented

### ISSUE THREAD

**Issue by NikolaiGassner** [CVVisualPSETeam/CVVisual#40]
There are no descriptions about what they do at the unit tests (needed for test document)
and the manual tests for dbg_printer, finalShowCrash and multiple calls .

**Comment by Fiona-J-W** [comment]
The unit-tests too? Most of them only test highly generic stuff like Reference or ObserverPtr. It would most likely be better to just mention that we have automatic test for:
- the debug-flag
- isAnyOf (a utility-algorithm)
- the Location-macro (CVVISUAL_LOCATION)
- ObserverPtr
- Reference

I fixed the other stuff you mentioned, I must have overlooked them for some reason when I ckecked before closing the original issue.
